language: node_js
php:
   - 'iojs'
   - 'node'
dist: trusty
sudo: required
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  yarn: true
before_script:
  - yarn add webpack webpack-cli --dev --flat
notifications:
  webhooks: https://outlook.office.com/webhook/f2e23e55-b57d-48c0-9dfe-2fa37bc0410d@307a54f4-8cde-4681-93af-be6cebf30c26/TravisCI/033549a0e1ff41f589ebab25048e2db4/789c31c2-6879-4c34-b444-4a6bfad6490e